//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "starboard_posts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_message_id: i64,
    pub guild_id: i64,
    pub source_channel_id: i64,
    pub starboard_message_id: i64,
    pub reaction_count: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
